name: Update Gradle Wrapper
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1